dapur_laekker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user
from main.views import edit_product, delete_product
from main.views import get_product_json, add_product_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name = 'show_main'),
    path('create-product/', create_product, name='create_product'),
    path('xml/', show_xml, name= 'show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Inventory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add = True)
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Inventory

class ProductForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ["name", "amount", "description"]

main/views.py
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.core import serializers
from main.models import Inventory
from main.forms import ProductForm
from django.shortcuts import render

@login_required(login_url='/login')
def show_main(request):
    inventories = Inventory.objects.filter(user=request.user)
    context = {
        'name': request.user.username,
        'class': 'PBP D',
        'products': inventories,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    
    context = {'form': form}
    return render(request, "create_product.html", context)


def show_xml(request):
    data = Inventory.objects.all()
    return HttpResponse(serializers.serialize('xml', data), 
                        content_type= 'application/xml')

def show_json(request):
    data = Inventory.objects.all()
    return HttpResponse(serializers.serialize('json', data),
                        content_type='application/json')

def show_xml_by_id(request, id):
    data = Inventory.objects.filter(pk=id)
    return HttpResponse(serializers.serialize('xml', data), 
                        content_type= 'application/xml')

def show_json_by_id(request, id):
    data = Inventory.objects.filter(pk=id)
    return HttpResponse(serializers.serialize('json', data),
                        content_type='application/json')

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Inventory.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    context = {'form': form}
    return render(request, 'edit_product.html', context)

def delete_product(request, id):
    # Get data berdasarkan ID
    product = Inventory.objects.get(pk = id)
    # Hapus data
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    product_item = Inventory.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Inventory(name=name, amount=amount,
                                description=description, user=user)
        new_product.save()

        return HttpResponse("CREATED", status=201)
    
    return HttpResponseNotFound()

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<div class="container">
    <h1 class="mt-4">Add New Product</h1>

    <form method="POST" class="mt-4">
        {% csrf_token %}
    
        <table class="table">
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <button type="submit" class="btn btn-primary">Add Product</button>
                </td>
            </tr>
        </table>
    </form>

</div>
{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="login-container">
        <h1 class="text-center">Login</h1>

        <form method="POST" action="" class="login-form">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">Username:</label>
                <input type="text" name="username" placeholder="Username" class="form-control">
            </div>

            <div class="mb-3">
                <label for="password" class="form-label">Password:</label>
                <input type="password" name="password" placeholder="Password" class="form-control">
            </div>

            <div class="mb-3">
                <input class="btn btn-primary" type="submit" value="Login">
            </div>
        </form>

        {% if messages %}
            <div class="alert alert-danger">
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <p class="text-center">Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
    </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="text-center mt-4">Inventory</h1>
    <h6 class="mt-4">Name:</h5>
    <p class="mt-1">{{name}}</p>

    <h6 class="mt-4">Class:</h5>
    <p class="mt-1">{{class}}</p>

    <div class="card-deck" id="product_container">
        {% for inventory in products %}
            <div class="card border-secondary mt-4">
                <div class="card-body">
                    <h5 class="card-title">{{inventory.name}}</h5>
                    <p class="card-text">Amount: {{inventory.amount}}</p>
                    <p class="card-text">Description: {{inventory.description}}</p>
                    <p class="card-text">Date Added: {{inventory.date_added}}</p>
                    <a href="{% url 'main:edit_product' inventory.pk %}" class="btn btn-primary">
                        Edit
                    </a>
                    <a href="{% url 'main:delete_product' inventory.pk %}" class="btn btn-danger">
                        Delete
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>

    <br />

    <a href="{% url 'main:create_product' %}" class="btn btn-primary mb-3">
        Add New Product
    </a>

    <button type="button" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Add New Product by AJAX
    </button>

    <h5 class="mt-3">Sesi terakhir login: {{ last_login }}</h5>

    <a href="{% url 'main:logout' %}" class="btn btn-light mb-3" style="background-color: lightgrey">
        Logout
    </a>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>

<script>
    refreshProducts();

    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        document.getElementById("product_container").innerHTML = `<div class="card-deck">${htmlString}</div>`
        const products = await getProducts()
        let htmlString = "";
        products.forEach((item) => {
            htmlString += `<div class="card">`;
            htmlString += `<div class="card-body">`;
            htmlString += `<h5 class="card-title">${item.fields.name}</h5>`;
            htmlString += `<p class="card-text">Amount: ${item.fields.amount}</p>`;
            htmlString += `<p class="card-text">Description: ${item.fields.description}</p>`;
            htmlString += `</div></div>`;

        });

        document.getElementById("product_container").innerHTML = `<div class="card-deck">${htmlString}</div>`
    }

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addProduct

</script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="register-container">
        <h1 class="text-center">Register</h1>

        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.as_p }}
            </div>

            <div class="mb-3">
                <input class="btn btn-success" type="submit" name="submit" value="Register"/>
            </div>
        </form>

        {% if messages %}
            <div class="alert alert-info">
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=1200, initial-scale=1.0">
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #A1CCD1;">
            <div class="container">
                <a class="navbar-brand h1" href="{% url 'main:show_main' %}">Dapur Laekker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mt-auto ml-auto">
                        <li class="nav-item h6">
                            <a class="nav-link" href="{% url 'main:show_main' %}">Home</a>
                        </li>
                        <li class="nav-item h6">
                            <a class="nav-link" href="{% url 'main:create_product' %}">Add Product</a>
                        </li>
                        <li class="nav-item h6">
                            <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>